FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY . .
#/Akkamart/Catalogs/Catalogs.csproj
RUN dotnet restore Akkamart/Catalogs/Catalogs.csproj
WORKDIR /src/Akkamart/Catalogs
RUN dotnet build --no-restore -o /app

FROM build AS publish
RUN dotnet publish --no-restore -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Catalogs.dll", "Catalogs.conf"] 