FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY . .
#/Akkamart/Inventory/Inventory.csproj
RUN dotnet restore Akkamart/Inventory/Inventory.csproj
WORKDIR /src/Akkamart/Inventory
RUN dotnet build --no-restore -o /app

FROM build AS publish
RUN dotnet publish --no-restore -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Inventory.dll", "Inventory.conf"] 