version: "3"
services:
  seed2:
    image: akkamart-seed2
    networks:
      - nodes_net
    environment:
      - SEED_NODE_HOST=seed2
      - OWN_HOST=seed2
  gateway:
    image: akkamart-gateway
    networks:
      - nodes_net
    environment:
      - SEED_NODE_HOST=seed2
    ports:
      - "5050:5050"
  credentials:
    image: akkamart-credentials
    networks:
      - nodes_net
    environment:
      - SEED_NODE_HOST=seed2
      - SQLSERVER_CONNECTION = Server=localhost,1433;Database=akkamart;User Id=sa;Password=(PHlx%IV2zbT&j3P;
  memberships:
    image: akkamart-memberships
    networks:
      - nodes_net
    environment:
      - SEED_NODE_HOST=seed2
      - SQLSERVER_CONNECTION = Server=localhost,1433;Database=akkamart;User Id=sa;Password=(PHlx%IV2zbT&j3P;
  smsmessanger:
    image: akkamart-smsmanager
    networks:
      - nodes_net
    environment:
      - SEED_NODE_HOST=seed2
      - SQLSERVER_CONNECTION = Server=localhost,1433;Database=akkamart;User Id=sa;Password=(PHlx%IV2zbT&j3P;
networks:
  nodes_net:
    driver: bridge
