FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY . .
#/Akkamart/Ordering/Ordering.csproj
RUN dotnet restore Akkamart/Ordering/Ordering.csproj
WORKDIR /src/Akkamart/Ordering
RUN dotnet build --no-restore -o /app

FROM build AS publish
RUN dotnet publish --no-restore -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Ordering.dll", "Ordering.conf"] 